import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useSession, signIn, signOut } from "next-auth/react";
import Post from "../components/Post";
import { useState } from "react";
import { server } from "../config/index";
import { useEffect } from "react";
export default function Home({ data }) {
  const { data: session } = useSession();
  const [newPost, setNewPost] = useState("");
  const [allPosts, setAllPosts] = useState();
  const [posts, setPosts] = useState();
  const [errMessage, setErrMessage] = useState("");
  const [postFilter, setFilter] = useState("all");
  async function submitPost(e) {
    e.preventDefault();
    fetch(`${server}/api/posts/create`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        uid: session?.user._id,
        username: session?.user.username,
        content: newPost,
      }),
    })
      .then((res) => res.json())
      .then((data) => {
        if (data.error) {
          console.log(data.message);
          setErrMessage(data.message);
          return;
        }
        console.log(data);
        setNewPost("");
        setErrMessage("");
        document.getElementById("postInput").value = "";
        setPosts((prevPosts) => [data, ...prevPosts]);
      });
  }
  useEffect(() => {
    setAllPosts(data.posts);
    setPosts(data.posts);
  }, []);

  function handleFilter(e) {
    // location.reload();
    if (e.target.value === "friends") {
      setPosts(
        posts.filter((post) => {
          if (session?.user?.friends.includes(post.uid)) {
            return post;
          }
        })
      );
    } else if (e.target.value === "all") {
      setPosts(allPosts);
    }
  }

  return (
    <div>
      <Head>
        <title>Social-Humans</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <div>
          <div style={{ width: "80%", margin: "0 auto" }}>
            <form
              onChange={(e) => {
                console.log(e.target.value);
                handleFilter(e);
              }}
            >
              <label id="filter" style={{ display: "inline-block" }}>
                Filter Posts:
              </label>
              <select
                style={{
                  backgroundColor: "black",
                  color: "white",
                  display: "inline-block",
                }}
                name="filter"
                id="filter"
              >
                <option value="all">all</option>
                <option value="friends">friends</option>
              </select>
            </form>

            {errMessage.length > 1 ? (
              <p style={{ color: "red" }}>{errMessage}</p>
            ) : (
              ""
            )}
            <form>
              <br />
              <div style={{ display: "flex", alignItems: "center" }}>
                <img
                  src="https://i.stack.imgur.com/34AD2.jpg"
                  style={{
                    display: "inline-block",
                    width: "30px",
                    height: "30px",
                    borderRadius: "50%",
                    margin: "5px",
                  }}
                />
                <input
                  id="postInput"
                  className={styles.postInput}
                  placeholder={`What's on your mind ${session?.user.username}?`}
                  onChange={(e) => {
                    setNewPost(e.target.value);
                  }}
                />
                <button
                  style={{ width: "20%", display: "none" }}
                  onClick={submitPost}
                >
                  Submit
                </button>
              </div>
            </form>
          </div>
          {data
            ? posts?.map((post) => {
                return <Post post={post} key={post._id} />;
              })
            : ""}
        </div>
      </div>
    </div>
  );
}

export async function getServerSideProps() {
  const res = await fetch(`${server}/api/posts`);
  const data = await res.json();
  return { props: { data } };
}
