import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useSession, signIn, signOut } from "next-auth/react";
import Post from "../components/Post";
import { useState } from "react";
import { server } from "../config/index";
import { useEffect } from "react";
export default function Home({ data }) {
  const { data: session } = useSession();
  const [newPost, setNewPost] = useState("");
  const [posts, setPosts] = useState();
  const [errMessage, setErrMessage] = useState("");
  async function submitPost(e) {
    e.preventDefault();
    fetch(`${server}/api/posts/create`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        uid: session?.user._id,
        username: session?.user.username,
        content: newPost,
      }),
    })
      .then((res) => res.json())
      .then((data) => {
        if (data.error) {
          console.log(data.message);
          setErrMessage(data.message);
          return;
        }
        console.log(data);
        setNewPost("");
        setErrMessage("");
        document.getElementById("postInput").value = "";
        setPosts((prevPosts) => [data, ...prevPosts]);
      });
  }
  useEffect(() => {
    setPosts(data.posts);
  }, []);
  return (
    <div>
      <Head>
        <title>Social-Humans</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <div style={{ border: "solid 1px yellow" }}>
          <div style={{ width: "80%", margin: "0 auto" }}>
            {errMessage.length > 1 ? (
              <p style={{ color: "red" }}>{errMessage}</p>
            ) : (
              ""
            )}
            <form>
              <br />
              <input
                id="postInput"
                placeholder={`what's on your mind ${session?.user.username}?`}
                style={{ width: "80%" }}
                onChange={(e) => {
                  setNewPost(e.target.value);
                }}
              />
              <button style={{ width: "20%" }} onClick={submitPost}>
                Submit
              </button>
            </form>
          </div>
          {data
            ? posts?.map((post) => {
                return <Post post={post} key={post._id} />;
              })
            : ""}
        </div>
        <div style={{ border: "solid 1px aqua" }}>yo</div>
      </div>
    </div>
  );
}

export async function getServerSideProps() {
  const res = await fetch(`${server}/api/posts`);
  const data = await res.json();
  return { props: { data } };
}
